apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: details-no-reuse
spec:
  host: details
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: ratings-no-reuse
spec:
  host: ratings
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: reviews-no-reuse
spec:
  host: reviews
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
---
# NOTE: allow connection reuse on incoming requests to productpage from ingress
# apiVersion: networking.istio.io/v1
# kind: DestinationRule
# metadata:
#   name: productpage-no-reuse
# spec:
#   host: productpage
#   trafficPolicy:
#     connectionPool:
#       http:
#         maxRequestsPerConnection: 1
