apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: $DOCKER_HUB
  tag: $DOCKER_TAG
  values:
    global:
      imagePullPolicy: Always
    telemetry:
      enabled: false
      v2:
        enabled: false
  components:
    pilot:
      k8s:
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        hpaSpec:
          maxReplicas: 1
        securityContext:
          supplementalGroups: [116]
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"
          limits:
            tpm.boxboat.io/tpmrm: 1
        overlays:
        - kind: Deployment
          name: istiod
          patches:
          - path: spec.template.spec.volumes[-1]
            value:
              name: mazu-config-volume
              configMap:
                name: mazu-config
          - path: spec.template.spec.volumes[-1]
            value:
              name: tpm-keys-volume
              secret:
                secretName: tpm-keys
          - path: spec.template.spec.volumes[-1]
            value:
              name: rbe-pp-volume
              configMap:
                name: rbe-pp
          - path: spec.template.spec.containers[name:discovery].volumeMounts[-1]
            value:
              name: mazu-config-volume
              mountPath: /etc/mazu-config
          - path: spec.template.spec.containers[name:discovery].volumeMounts[-1]
            value:
              name: tpm-keys-volume
              mountPath: /etc/tpm-keys
          - path: spec.template.spec.containers[name:discovery].volumeMounts[-1]
            value:
              name: rbe-pp-volume
              mountPath: /var/run/rbe-pp
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
        hpaSpec:
          minReplicas: 10
          maxReplicas: 10
        overlays:
        - kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.volumes[-1]
            value:
              name: mazu-config-volume
              configMap:
                name: mazu-config
          - path: spec.template.spec.volumes[-1]
            value:
              name: tpm-keys-volume
              secret:
                secretName: tpm-keys
          - path: spec.template.spec.volumes[-1]
            value:
              name: rbe-pp-volume
              configMap:
                name: rbe-pp
          - path: spec.template.spec.containers[name:istio-proxy].volumeMounts[-1]
            value:
              name: mazu-config-volume
              mountPath: /etc/mazu-config
          - path: spec.template.spec.containers[name:istio-proxy].volumeMounts[-1]
            value:
              name: tpm-keys-volume
              mountPath: /etc/tpm-keys
          - path: spec.template.spec.containers[name:istio-proxy].volumeMounts[-1]
            value:
              name: rbe-pp-volume
              mountPath: /var/run/rbe-pp